
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 07 16:30:21 BRT 2024
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int DECIMAL = 14;
  public static final int INTEIRO = 13;
  public static final int MAIOR = 9;
  public static final int PROGRAMA = 2;
  public static final int PARENTESESOPEN = 11;
  public static final int TIPO_DECIMAL = 6;
  public static final int PARENTESESCLOSE = 10;
  public static final int MULT = 8;
  public static final int TIPO_INTEIRO = 5;
  public static final int PTVG = 12;
  public static final int INICIO = 3;
  public static final int EOF = 0;
  public static final int FIM = 4;
  public static final int OPERADORESLOGICOS = 7;
  public static final int IGUAL = 16;
  public static final int error = 1;
  public static final int VARIAVEL = 15;
}

